# https://taskfile.dev

version: '3'


tasks:
  build:
    desc: Build for Docker Hub
    cmds:
      - docker build -t alastairhm/ansible-lint:latest ./
    silent: true
  push:
    desc: Push to Docker Hub
    cmds:
      - docker push alastairhm/ansible-lint:latest
    silent: true
